# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SoFi' do
  use_frameworks!

  # Pods for SoFi
  pod 'AlamofireImage'#, '~> 3.3'

  target 'SoFiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoFiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
